In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('uber_trips.csv')
df.head()

         start_date          end_date  ... miles          purpose
0  01/01/2016 21:11  01/01/2016 21:17  ...   5.1   Meal/Entertain
1  02/01/2016 01:25  02/01/2016 01:37  ...   5.0              NaN
2  02/01/2016 20:25  02/01/2016 20:38  ...   4.8  Errand/Supplies
3  05/01/2016 17:31  05/01/2016 17:45  ...   4.7          Meeting
4  06/01/2016 14:42  06/01/2016 15:49  ...  63.7   Customer Visit

[5 rows x 7 columns]

In [0]:
# Demanda: Você recebe uma tabela de corridas do Uber que contém a quilometragem e o objetivo da despesa comercial. Você é solicitado a encontrar objetivos comerciais que gerem o maior número de milhas percorridas para passageiros que usam o Uber para transporte comercial. Encontre as 3 principais categorias de finalidade comercial por quilometragem total.

df_business = df[df['category'] == 'Business']
df_miles_by_purpose = df_business.groupby(by='purpose')['miles'].sum().reset_index()
top_3_purposes = df_miles_by_purpose.nlargest(3, 'miles')
top_3_purposes

          purpose  miles
5         Meeting  283.9
2  Customer Visit  241.1
4  Meal/Entertain   78.0